import { Card, Hand } from "./cards";

export type Seat = "N" | "E" | "S" | "W";

export type PlayDeal = {
  id: string;
  title: string;
  lesson: string;
  contract: string;
  declarer: Seat;
  trumpSuit: "S" | "H" | "D" | "C" | "NT";
  leader: Seat;
  openingLead: Card;
  hands: {
    north: Hand;
    east: Hand;
    south: Hand;
    west: Hand;
  };
  coachingTip: string;
};

export const PLAY_DEALS: PlayDeal[] = [
  {
    id: "draw-trumps-4s",
    title: "Declarer Play: Draw Trumps",
    lesson:
      "You are in 4♠. The main lesson is to draw trumps before cashing side-suit winners.",
    contract: "4S",
    declarer: "S",
    trumpSuit: "S",
    leader: "W",
    openingLead: { suit: "H", rank: "K" },
    coachingTip:
      "After winning the first trick, declarer should usually draw trumps before cashing outside winners. This prevents defenders from ruffing your good cards.",
    hands: {
      north: [
        { suit: "S", rank: "Q" },
        { suit: "S", rank: "7" },
        { suit: "S", rank: "4" },
        { suit: "H", rank: "8" },
        { suit: "H", rank: "5" },
        { suit: "D", rank: "A" },
        { suit: "D", rank: "Q" },
        { suit: "D", rank: "7" },
        { suit: "D", rank: "3" },
        { suit: "C", rank: "K" },
        { suit: "C", rank: "8" },
        { suit: "C", rank: "6" },
        { suit: "C", rank: "2" },
      ],
      east: [
        { suit: "S", rank: "9" },
        { suit: "S", rank: "6" },
        { suit: "H", rank: "Q" },
        { suit: "H", rank: "J" },
        { suit: "H", rank: "9" },
        { suit: "H", rank: "4" },
        { suit: "D", rank: "T" },
        { suit: "D", rank: "8" },
        { suit: "D", rank: "5" },
        { suit: "C", rank: "Q" },
        { suit: "C", rank: "J" },
        { suit: "C", rank: "7" },
        { suit: "C", rank: "3" },
      ],
      south: [
        { suit: "S", rank: "A" },
        { suit: "S", rank: "K" },
        { suit: "S", rank: "J" },
        { suit: "S", rank: "T" },
        { suit: "S", rank: "8" },
        { suit: "S", rank: "3" },
        { suit: "H", rank: "A" },
        { suit: "H", rank: "7" },
        { suit: "H", rank: "2" },
        { suit: "D", rank: "K" },
        { suit: "D", rank: "6" },
        { suit: "C", rank: "A" },
        { suit: "C", rank: "5" },
      ],
      west: [
        { suit: "S", rank: "5" },
        { suit: "S", rank: "2" },
        { suit: "H", rank: "K" },
        { suit: "H", rank: "T" },
        { suit: "H", rank: "6" },
        { suit: "H", rank: "3" },
        { suit: "D", rank: "J" },
        { suit: "D", rank: "9" },
        { suit: "D", rank: "4" },
        { suit: "D", rank: "2" },
        { suit: "C", rank: "T" },
        { suit: "C", rank: "9" },
        { suit: "C", rank: "4" },
      ],
    },
  },

  {
    id: "establish-long-suit-3nt",
    title: "Declarer Play: Establish a Long Suit",
    lesson:
      "You are in 3NT. The main lesson is to establish dummy's long diamond suit before cashing all your quick winners.",
    contract: "3NT",
    declarer: "S",
    trumpSuit: "NT",
    leader: "W",
    openingLead: { suit: "S", rank: "Q" },
    coachingTip:
      "In no trumps, count your winners. If you do not have enough immediate winners, look for a long suit to establish. Here, diamonds are the suit to develop.",
    hands: {
      north: [
        { suit: "S", rank: "8" },
        { suit: "S", rank: "4" },
        { suit: "H", rank: "K" },
        { suit: "H", rank: "6" },
        { suit: "H", rank: "3" },
        { suit: "D", rank: "A" },
        { suit: "D", rank: "Q" },
        { suit: "D", rank: "J" },
        { suit: "D", rank: "T" },
        { suit: "D", rank: "7" },
        { suit: "C", rank: "8" },
        { suit: "C", rank: "5" },
        { suit: "C", rank: "2" },
      ],
      east: [
        { suit: "S", rank: "K" },
        { suit: "S", rank: "7" },
        { suit: "S", rank: "3" },
        { suit: "H", rank: "Q" },
        { suit: "H", rank: "T" },
        { suit: "H", rank: "7" },
        { suit: "D", rank: "9" },
        { suit: "D", rank: "5" },
        { suit: "D", rank: "2" },
        { suit: "C", rank: "Q" },
        { suit: "C", rank: "J" },
        { suit: "C", rank: "9" },
        { suit: "C", rank: "4" },
      ],
      south: [
        { suit: "S", rank: "A" },
        { suit: "S", rank: "J" },
        { suit: "S", rank: "6" },
        { suit: "S", rank: "2" },
        { suit: "H", rank: "A" },
        { suit: "H", rank: "J" },
        { suit: "H", rank: "4" },
        { suit: "D", rank: "K" },
        { suit: "D", rank: "6" },
        { suit: "D", rank: "3" },
        { suit: "C", rank: "A" },
        { suit: "C", rank: "K" },
        { suit: "C", rank: "3" },
      ],
      west: [
        { suit: "S", rank: "Q" },
        { suit: "S", rank: "T" },
        { suit: "S", rank: "9" },
        { suit: "S", rank: "5" },
        { suit: "H", rank: "9" },
        { suit: "H", rank: "8" },
        { suit: "H", rank: "5" },
        { suit: "H", rank: "2" },
        { suit: "D", rank: "8" },
        { suit: "D", rank: "4" },
        { suit: "C", rank: "T" },
        { suit: "C", rank: "7" },
        { suit: "C", rank: "6" },
      ],
    },
  },

  {
    id: "preserve-entries-3nt",
    title: "Declarer Play: Preserve Entries",
    lesson:
      "You are in 3NT. The main lesson is to preserve entries to dummy so you can enjoy established winners later.",
    contract: "3NT",
    declarer: "S",
    trumpSuit: "NT",
    leader: "W",
    openingLead: { suit: "H", rank: "Q" },
    coachingTip:
      "Before playing to trick one, ask: where are my entries? If dummy has a suit that may become good, do not casually use dummy's only entry too early.",
    hands: {
      north: [
        { suit: "S", rank: "K" },
        { suit: "S", rank: "5" },
        { suit: "S", rank: "2" },
        { suit: "H", rank: "8" },
        { suit: "H", rank: "4" },
        { suit: "D", rank: "Q" },
        { suit: "D", rank: "J" },
        { suit: "D", rank: "T" },
        { suit: "D", rank: "9" },
        { suit: "D", rank: "3" },
        { suit: "C", rank: "7" },
        { suit: "C", rank: "5" },
        { suit: "C", rank: "2" },
      ],
      east: [
        { suit: "S", rank: "Q" },
        { suit: "S", rank: "9" },
        { suit: "S", rank: "7" },
        { suit: "H", rank: "K" },
        { suit: "H", rank: "T" },
        { suit: "H", rank: "6" },
        { suit: "D", rank: "8" },
        { suit: "D", rank: "5" },
        { suit: "D", rank: "2" },
        { suit: "C", rank: "Q" },
        { suit: "C", rank: "J" },
        { suit: "C", rank: "9" },
        { suit: "C", rank: "4" },
      ],
      south: [
        { suit: "S", rank: "A" },
        { suit: "S", rank: "J" },
        { suit: "S", rank: "T" },
        { suit: "S", rank: "4" },
        { suit: "H", rank: "A" },
        { suit: "H", rank: "J" },
        { suit: "H", rank: "3" },
        { suit: "D", rank: "A" },
        { suit: "D", rank: "7" },
        { suit: "D", rank: "6" },
        { suit: "C", rank: "A" },
        { suit: "C", rank: "K" },
        { suit: "C", rank: "3" },
      ],
      west: [
        { suit: "S", rank: "8" },
        { suit: "S", rank: "6" },
        { suit: "S", rank: "3" },
        { suit: "H", rank: "Q" },
        { suit: "H", rank: "9" },
        { suit: "H", rank: "7" },
        { suit: "H", rank: "5" },
        { suit: "H", rank: "2" },
        { suit: "D", rank: "K" },
        { suit: "D", rank: "4" },
        { suit: "C", rank: "T" },
        { suit: "C", rank: "8" },
        { suit: "C", rank: "6" },
      ],
    },
  },

  {
    id: "ruff-losers-in-dummy-4h",
    title: "Declarer Play: Ruff Losers in Dummy",
    lesson:
      "You are in 4♥. The main lesson is to use dummy's short suit to ruff losing cards before drawing all the trumps.",
    contract: "4H",
    declarer: "S",
    trumpSuit: "H",
    leader: "W",
    openingLead: { suit: "S", rank: "K" },
    coachingTip:
      "In a suit contract, count your losers. If dummy is short in a side suit, you may need to ruff losers in dummy before drawing every trump.",
    hands: {
      north: [
        { suit: "S", rank: "8" },
        { suit: "S", rank: "4" },
        { suit: "H", rank: "Q" },
        { suit: "H", rank: "7" },
        { suit: "H", rank: "5" },
        { suit: "D", rank: "A" },
        { suit: "D", rank: "9" },
        { suit: "D", rank: "6" },
        { suit: "D", rank: "3" },
        { suit: "C", rank: "K" },
        { suit: "C", rank: "Q" },
        { suit: "C", rank: "8" },
        { suit: "C", rank: "2" },
      ],
      east: [
        { suit: "S", rank: "Q" },
        { suit: "S", rank: "T" },
        { suit: "S", rank: "7" },
        { suit: "H", rank: "9" },
        { suit: "H", rank: "4" },
        { suit: "D", rank: "K" },
        { suit: "D", rank: "J" },
        { suit: "D", rank: "8" },
        { suit: "C", rank: "J" },
        { suit: "C", rank: "T" },
        { suit: "C", rank: "7" },
        { suit: "C", rank: "5" },
        { suit: "C", rank: "3" },
      ],
      south: [
        { suit: "S", rank: "A" },
        { suit: "S", rank: "9" },
        { suit: "S", rank: "6" },
        { suit: "S", rank: "3" },
        { suit: "H", rank: "A" },
        { suit: "H", rank: "K" },
        { suit: "H", rank: "J" },
        { suit: "H", rank: "T" },
        { suit: "H", rank: "8" },
        { suit: "D", rank: "Q" },
        { suit: "D", rank: "5" },
        { suit: "C", rank: "A" },
        { suit: "C", rank: "4" },
      ],
      west: [
        { suit: "S", rank: "K" },
        { suit: "S", rank: "J" },
        { suit: "S", rank: "5" },
        { suit: "S", rank: "2" },
        { suit: "H", rank: "6" },
        { suit: "H", rank: "3" },
        { suit: "H", rank: "2" },
        { suit: "D", rank: "T" },
        { suit: "D", rank: "7" },
        { suit: "D", rank: "4" },
        { suit: "D", rank: "2" },
        { suit: "C", rank: "9" },
        { suit: "C", rank: "6" },
      ],
    },
  },

  {
    id: "take-a-finesse-4s",
    title: "Declarer Play: Taking a Finesse",
    lesson:
      "You are in 4♠. The main lesson is to recognise when a finesse may avoid a loser.",
    contract: "4S",
    declarer: "S",
    trumpSuit: "S",
    leader: "W",
    openingLead: { suit: "D", rank: "K" },
    coachingTip:
      "A finesse is an attempt to win a trick with a lower honour by hoping a higher honour is favourably placed. Think about which opponent you need to hold the missing honour.",
    hands: {
      north: [
        { suit: "S", rank: "Q" },
        { suit: "S", rank: "8" },
        { suit: "S", rank: "4" },
        { suit: "H", rank: "A" },
        { suit: "H", rank: "Q" },
        { suit: "H", rank: "5" },
        { suit: "D", rank: "8" },
        { suit: "D", rank: "4" },
        { suit: "D", rank: "2" },
        { suit: "C", rank: "K" },
        { suit: "C", rank: "J" },
        { suit: "C", rank: "7" },
        { suit: "C", rank: "3" },
      ],
      east: [
        { suit: "S", rank: "9" },
        { suit: "S", rank: "6" },
        { suit: "H", rank: "K" },
        { suit: "H", rank: "T" },
        { suit: "H", rank: "8" },
        { suit: "D", rank: "Q" },
        { suit: "D", rank: "J" },
        { suit: "D", rank: "7" },
        { suit: "C", rank: "Q" },
        { suit: "C", rank: "T" },
        { suit: "C", rank: "8" },
        { suit: "C", rank: "5" },
        { suit: "C", rank: "2" },
      ],
      south: [
        { suit: "S", rank: "A" },
        { suit: "S", rank: "K" },
        { suit: "S", rank: "J" },
        { suit: "S", rank: "T" },
        { suit: "S", rank: "7" },
        { suit: "S", rank: "3" },
        { suit: "H", rank: "J" },
        { suit: "H", rank: "9" },
        { suit: "H", rank: "4" },
        { suit: "D", rank: "A" },
        { suit: "D", rank: "6" },
        { suit: "C", rank: "A" },
        { suit: "C", rank: "4" },
      ],
      west: [
        { suit: "S", rank: "5" },
        { suit: "S", rank: "2" },
        { suit: "H", rank: "7" },
        { suit: "H", rank: "6" },
        { suit: "H", rank: "3" },
        { suit: "H", rank: "2" },
        { suit: "D", rank: "K" },
        { suit: "D", rank: "T" },
        { suit: "D", rank: "9" },
        { suit: "D", rank: "5" },
        { suit: "D", rank: "3" },
        { suit: "C", rank: "9" },
        { suit: "C", rank: "6" },
      ],
    },
  },

  {
    id: "hold-up-play-3nt",
    title: "Declarer Play: Hold-Up Play",
    lesson:
      "You are in 3NT. The main lesson is to consider holding up an ace to cut communication between defenders.",
    contract: "3NT",
    declarer: "S",
    trumpSuit: "NT",
    leader: "W",
    openingLead: { suit: "S", rank: "K" },
    coachingTip:
      "In no trumps, if defenders attack your weak suit, sometimes you should hold up your ace. The aim is to exhaust one defender of that suit and break their communication.",
    hands: {
      north: [
        { suit: "S", rank: "8" },
        { suit: "S", rank: "6" },
        { suit: "S", rank: "3" },
        { suit: "H", rank: "K" },
        { suit: "H", rank: "Q" },
        { suit: "H", rank: "7" },
        { suit: "D", rank: "A" },
        { suit: "D", rank: "J" },
        { suit: "D", rank: "9" },
        { suit: "D", rank: "4" },
        { suit: "C", rank: "Q" },
        { suit: "C", rank: "8" },
        { suit: "C", rank: "2" },
      ],
      east: [
        { suit: "S", rank: "J" },
        { suit: "S", rank: "9" },
        { suit: "S", rank: "4" },
        { suit: "H", rank: "T" },
        { suit: "H", rank: "8" },
        { suit: "H", rank: "5" },
        { suit: "D", rank: "Q" },
        { suit: "D", rank: "8" },
        { suit: "D", rank: "5" },
        { suit: "C", rank: "J" },
        { suit: "C", rank: "T" },
        { suit: "C", rank: "6" },
        { suit: "C", rank: "3" },
      ],
      south: [
        { suit: "S", rank: "A" },
        { suit: "S", rank: "7" },
        { suit: "S", rank: "2" },
        { suit: "H", rank: "A" },
        { suit: "H", rank: "J" },
        { suit: "H", rank: "4" },
        { suit: "D", rank: "K" },
        { suit: "D", rank: "T" },
        { suit: "D", rank: "7" },
        { suit: "C", rank: "A" },
        { suit: "C", rank: "K" },
        { suit: "C", rank: "9" },
        { suit: "C", rank: "4" },
      ],
      west: [
        { suit: "S", rank: "K" },
        { suit: "S", rank: "Q" },
        { suit: "S", rank: "T" },
        { suit: "S", rank: "5" },
        { suit: "H", rank: "9" },
        { suit: "H", rank: "6" },
        { suit: "H", rank: "3" },
        { suit: "H", rank: "2" },
        { suit: "D", rank: "6" },
        { suit: "D", rank: "3" },
        { suit: "D", rank: "2" },
        { suit: "C", rank: "7" },
        { suit: "C", rank: "5" },
      ],
    },
  },
];